### ISSUE TITLE
DATOS A TOMAR EN CUENTA 

### ISSUE THREAD

**Issue by TheLocoto** [zrock-dev/Project_X#24]
- La docente pide obligatoriamente hacer uso de interfaces y clases abstractas. Por lo que dividir el codigo en modulos resulta una buena solucion para poder implementar estas. 

- No tener variables permanentes, ya que nos dijo que debemos de tener la forma de poder modificar las variables en el momento que queramos (como el ejemplo del precio de peliculas este no puede ser siempre 50bs, si no que puede bajar o aumentar)

- Dividir el trabajo en modulos 
- Mejorar el orden y la estructura del codigo

**Comment by zrock-dev** [comment]
Estoy moviendo este issue a la seccion de comentarios #33.
