### ISSUE TITLE
Correciones - rama - console Interface 

### ISSUE THREAD

**Issue by SilverWolf124** [zrock-dev/Project_X#70]
-Informacion cliente
Solo se puede pedir su ci al cliente una sola vez a la hora de comprar un ticket para la pelicula, con este CI el programa revisa si este cliente esta registrado y toma acciones en base a esa infomacion.
-Fecha de nacimiento | 03/01/2001 | DD/MM/AAAA
Que muestre un ejemplo del formato de fecha.
Forzar que el fomato sea el correcto.
-Cartela del cine
Cuando el codigo este corriendo solo se debe generar una vez.

**Comment by zrock-dev** [comment]
@SilverWolf124, la parte de generar la cartelera una sola vez ya la revise.

**Comment by SilverWolf124** [comment]
> @SilverWolf124, la parte de generar la cartelera una sola vez ya la revise.

Dale entonces omito esa parte

**Comment by zrock-dev** [comment]
fixed by #72
